Improve error detection around loading config file

diff --git a/punch b/punch
--- a/punch
+++ b/punch
@@ -122,7 +122,13 @@ findConfig() {
 
 config_file=$(findConfig)
 if [ ! -z "$config_file" ]; then
+	set +e
 	source "$config_file"
+	if [ $? != 0 ]; then
+		echo "Failed to source config file: $config_file" >&2
+		exit 1
+	fi
+	set -e
 fi
 
 while getopts ":f:dqh" opt; do
