Fix help references to non-PUNCH-prefixed variables

diff --git a/punch b/punch
--- a/punch
+++ b/punch
@@ -234,7 +234,7 @@ command_run() {
 		if [ -n "${PUNCH_IMAGE:-}" ]; then
 			AMI=$(find_image_with_distro $PUNCH_IMAGE)
 		else
-			echo "AMI or IMAGE is required for run command, either via -i command-line option or AMI environment variable" >&2
+			echo "PUNCH_AMI or PUNCH_IMAGE is required for run command, either via -i command-line option or PUNCH_AMI environment variable" >&2
 			exit 1
 		fi
 	fi
